# Server
server.port=8081
spring.application.name=tts-dashboard

#  MySQL DataSource
spring.datasource.url=jdbc:mysql://49.50.116.241:3306/tts_dataset?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=4piwu5%@4@RtQ^&6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#  HikariCP Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

#  JPA  disable DDL (you manage schema manually)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# JSP View Resolver
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Static Resources
spring.mvc.static-path-pattern=/static/**
spring.web.resources.static-locations=classpath:/static/

# Logging
logging.level.com.ttsstudio=DEBUG
logging.level.org.springframework.web=INFO